<1>Se esperaba 
<2> cadena de caracteres
<3>o se permite
<4> archivo
<5> constante
<6>una variable
<7> de 
<8>una expresion
<9> entera
<A> invalid
<B>dentificador
<C>o 
<D>er
<E>en
<F>aqui

01<1>';'
02<1>':'
03<1>','
04<1>'('
05<1>')'
06<1>'='
07<1>':='
08<1>'['
09<1>']'
10<1>'.'
11<1>'..'
12<1>BEGIN
13<1>DO
14<1>END
15<1>OF
16<1>PROCEDURE <C>FUNCTION
17<1>THEN
18<1>TO <C>DOWNTO
20<1><8> booleana
21<1><6><4>
22<1>una<5><9>
23<1><8><9>
24<1><6><9>
25<1>una<5><9> <C>real
26<1><8><9> <C>real
27<1><6><9> <C>real
28<1><6> punt<D>o
29<1><6> registro
30<1>un tip<C>simple
31<1><8> simple
32<1>una<5><2>
33<1><8><2>
34<1><6><2>
35<1>un<4><7>texto
36<1>un i<B><7>tipo
37<1>un<4> sin tipo
40Etiqueta indefinida
41I<B> desconocid<C><C><D>ror<7>sintaxis
42Tip<C>punt<D><C>indefinid<C><E> las definiciones<7>tipos previas
43I<B> <C>etiqueta duplicado
44Discordancia<7>tipos
45Constgante fu<D>a<7>rango
46La<5> y el selector CASE n<C>concu<D>dan <E> tipo
47Los tipos<7>los op<D>andos n<C>concu<D>dan con el opo<D>ador
48Tipo<7>resultado<A>o
49Longitud de<2><A>a
50La longitud<7>la<5><2> n<C>concu<D>da con el tipo
51Tip<C>subrang<C>base<A>o
52Limite inf<D>ior mayor que limite sup<D>ior
53Palabra res<D>vada
54Asignacion ilegal
55Constante de<2> que sobrepasa la linea
56Error <E><5><9>
57Error <E><5> real
58Caract<D> ilegal <E> i<B>
60N<3>n<5>s <F>
61N<3>n<4>s ni punt<D>os <F>
62N<3>n variables con estructura <F>
63N<3>n<4>s<7>text<C><F>
64N<3>n<4>s<7>text<C>ni sin tip<C><F>
65N<3>n<4>s sin tip<C><F>
66N<3> <E>trada/salida
67Los<4>s deb<E> s<D> parametros por variable
68Los compon<E>tes<7>un<4> n<C>pued<E> s<D><4>s
69Ord<E>ami<E>to<A>o<7>campos
70Tip<C>base para conjunt<C>fu<D>a<7>rango
71GOTO<A>o
72Etiqueta fu<D>a del bloque actual
73Procedimi<E>t<C>FORWARD indefinido
74Error INLINE
75Us<C>ilegal<7>ABSOLUTE
76Los ov<D>lays n<C>pued<E> s<D> FORWARD
77Los ov<D>lays n<3>n <E> mod<C>directo
90Archiv<C>n<C><E>contrado
91Final<7>fu<E>te inesp<D>ado
92Imposible crear<4><7>ov<D>lay
93Directiva<7>compilacion<A>a
96N<3> anidar includes
97Anidami<E>t<C>excesivo<7>WITHs
98Desbordami<E>to<7>memoria
99Desbordami<E>t<C>del compilador
