 «d
 a™¼lowedğÄ7
®onst•t
 v½iabœ
 exp™ssion€
ert
Inv¼i”ÀŒA
t¶
 doesm²ch
 i³µifi…
º›re¼
Str“g
s h…e
iœ
 not 
»define”
nteg…
 o=
Illegal 
ini
d N
anJ
'€n
Textf
or{
reS
‘ut¡r•ge
‘r 
leQ
n‡”f
s®•be f
v…lay
 ‡_
‘f 
‘v…flow
 “ 
abel
cti
o“t…
ƒ€^
…¸oun
 œngth
¸ase 
expe¥e
ompil…
 •”
 cC
Err˜£
Fv
Simpœ
atT
dep
este”
ntR
ype
 …r˜
 bB
 mH
If
Unh
alH
arh
ceF
di™¥

01';–
02':–
03',–
04'(–
05')–
06'=–
07':=–
08'[–
09']–
10'.–
11'..–
12BEGIN€
13DO€
14END€
15OF€
16PROCEDURE›FUNCTION€
17THEN€
18TO›DOWNTO€
20Booœ•„
21°§
22º‚€
23º„
24º§
25Š‚€
26Š„
27Š§
28P¦§
29Rec˜d§
30± €
31±„
32‹‚€
33‹„
34‹§
35—€
36T¶‰€
37U€
40l¤
41»known‰›syµax·
42p¦ £p™¾d“g  ³f“itions
43Duplic²e‰›l¤
44T¶¹ism²ch
45‚š
46‚­CASE seœ¥˜ ˆ
47Op…•”‡(s)ˆ‘p…²˜
48†™sult 
49†‹©
50‹‚©ˆ 
51†subr•geª
52Low¨”> upp¨d
53Res…ve”w˜d
54’assignmeµ
55‹‚ ex¾eds l“e
56¯i‚
57¯™¼‚
58’ch½a¥… “‰
60‚Œ
61°s­p¦Œ
62Stru¥u™dƒŒ
63—Œ
64—s­uŒ
65UŒ
66I/O
67°s¹ust¸eƒ p½amet…s
68°®omponeµs
69†˜d…“g¡fields
70Setªš
71†GOTO
72L¤with“®ur™µ¸lock
73FORWARD pro¾du™(s)
74INLINE·
75’use¡ABSOLUTE
76OŸ˜w½³d
77OŸs£¿¹o³
90°found
91»«”end¡sour¾
92»abœ to®™²e‘Ÿ f
93†c¬ ¿ive
96N´“clu³
97Too¹•y n´WITH's
98Mem˜y¢
99C¬¢
