01Se esperaba ';'
02Se esperaba ':'
03Se esperaba ','
04Se esperaba '('
05Se esperaba ')'
06Se esperaba '='
07Se esperaba ':='
08Se esperaba '['
09Se esperaba ']'
10Se esperaba '.'
11Se esperaba '..'
12Se esperaba BEGIN
13Se esperaba DO
14Se esperaba END
15Se esperaba OF
16Se esperaba PROCEDURE o FUNCTION
17Se esperaba THEN
18Se esperaba TO o DOWNTO
20Se esperaba una expresion booleana
21Se esperaba una variable archivo
22Se esperaba una constante entera
23Se esperaba una expresion entera
24Se esperaba una variable entera
25Se esperaba una constante entera o real
26Se esperaba una expresion entera o real
27Se esperaba una variable entera o real
28Se esperaba una variable puntero
29Se esperaba una variable registro
30Se esperaba un tipo simple
31Se esperaba una expresion simple
32Se esperaba una constante cadena de caracteres
33Se esperaba una expresion cadena de caracteres
34Se esperaba una variable cadena de caracteres
35Se esperaba un archivo de texto
36Se esperaba un identificador de tipo
37Se esperaba un archivo sin tipo
40Etiqueta indefinida
41Identificador desconocido o error de sintaxis
42Tipo puntero indefinido en las definiciones de tipos previas
43Identificador o etiqueta duplicado
44Discordancia de tipos
45Constgante fuera de rango
46La constante y el selector CASE no concuerdan en tipo
47Los tipos de los operandos no concuerdan con el opoerador
48Tipo de resultado invalido
49Longitud de cadena de caracteres invalida
50La longitud de la constante cadena de caracteres no concuerda con el tipo
51Tipo subrango base invalido
52Limite inferior mayor que limite superior
53Palabra reservada
54Asignacion ilegal
55Constante de cadena de caracteres que sobrepasa la linea
56Error en constante entera
57Error en constante real
58Caracter ilegal en identificador
60No se permiten constantes aqui
61No se permiten archivos ni punteros aqui
62No se permiten variables con estructura aqui
63No se permiten archivos de texto aqui
64No se permiten archivos de texto ni sin tipo aqui
65No se permiten archivos sin tipo aqui
66No se permite entrada/salida
67Los archivos deben ser parametros por variable
68Los componentes de un archivo no pueden ser archivos
69Ordenamiento invalido de campos
70Tipo base para conjunto fuera de rango
71GOTO invalido
72Etiqueta fuera del bloque actual
73Procedimiento FORWARD indefinido
74Error INLINE
75Uso ilegal de ABSOLUTE
76Los overlays no pueden ser FORWARD
77Los overlays no se permiten en modo directo
90Archivo no encontrado
91Final de fuente inesperado
92Imposible crear archivo de overlay
93Directiva de compilacion invalida
96No se permite anidar includes
97Anidamiento excesivo de WITHs
98Desbordamiento de memoria
99Desbordamiento del compilador
